// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePin(arg1) {
  return window['go']['main']['App']['ChangePin'](arg1);
}

export function CheckSecurityQuestion(arg1, arg2) {
  return window['go']['main']['App']['CheckSecurityQuestion'](arg1, arg2);
}

export function DelPass(arg1) {
  return window['go']['main']['App']['DelPass'](arg1);
}

export function FetchCredDetails() {
  return window['go']['main']['App']['FetchCredDetails']();
}

export function FetchPass(arg1) {
  return window['go']['main']['App']['FetchPass'](arg1);
}

export function GenPass(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenPass'](arg1, arg2, arg3, arg4);
}

export function GenerateRSAKeys() {
  return window['go']['main']['App']['GenerateRSAKeys']();
}

export function IsNew() {
  return window['go']['main']['App']['IsNew']();
}

export function Login_cred(arg1) {
  return window['go']['main']['App']['Login_cred'](arg1);
}

export function SetPin(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPin'](arg1, arg2, arg3);
}

export function StorePass(arg1, arg2, arg3) {
  return window['go']['main']['App']['StorePass'](arg1, arg2, arg3);
}
