// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangePin(arg1:string):Promise<void>;

export function CheckSecurityQuestion(arg1:string,arg2:string):Promise<boolean>;

export function DelPass(arg1:string):Promise<void>;

export function FetchCredDetails():Promise<Array<string>>;

export function FetchPass(arg1:string):Promise<Array<string>>;

export function GenPass(arg1:number,arg2:boolean,arg3:boolean,arg4:boolean):Promise<string>;

export function GenerateRSAKeys():Promise<void>;

export function IsNew():Promise<boolean>;

export function Login_cred(arg1:string):Promise<boolean>;

export function SetPin(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StorePass(arg1:string,arg2:string,arg3:string):Promise<void>;
